name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar el código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🧪 Correr tests con coverage
        run: npm run test -- --coverage

        